In [0]:
import numpy as np
import pandas as pd

In [2]:
# Question 1
consecutiveNaturalNum = np.arange(18).reshape(6, 3)
print("consecutive Natural Numbers::\n{}".format(consecutiveNaturalNum))

consecutive Natural Numbers::
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [3]:
# Question 2
df = pd.read_excel("Week 1 Dataset.xlsx")

df2 = df.rename(columns={"Name": "FirstName", "Income per month": "Income",
                         "State": "State_name", "Age": "Age_Num", "Sex": "Gender", "Number of siblings": "Siblings"})
print(df2)

  FirstName  Income     State_name  Age_Num Gender  Siblings
0         A      50     Tamil Nadu       23      M         0
1         B      34      Karnataka       37      F         3
2         C      54     Tamil Nadu       35      F         1
3         D      24  Uttar Pradesh       26      F         4
4         E      19          Bihar       59      M         5
5         F      21          Bihar       48      M         6
6         G      40          Delhi       30      F         2
7         H      20  Uttar Pradesh       72      M        10
8         I      30      Telangana       22      F         0
9         J      18    Chattisgarh       42      M         7


In [4]:
# Question 3

df.rename(columns={"Name": "FirstName", "Income per month": "Income",
                   "State": "State_name", "Age": "Age_Num", "Sex": "Gender",
                   "Number of siblings": "Siblings"}, inplace=True)
print(df)
print(df[["FirstName", "State_name", "Age_Num"]])

  FirstName  Income     State_name  Age_Num Gender  Siblings
0         A      50     Tamil Nadu       23      M         0
1         B      34      Karnataka       37      F         3
2         C      54     Tamil Nadu       35      F         1
3         D      24  Uttar Pradesh       26      F         4
4         E      19          Bihar       59      M         5
5         F      21          Bihar       48      M         6
6         G      40          Delhi       30      F         2
7         H      20  Uttar Pradesh       72      M        10
8         I      30      Telangana       22      F         0
9         J      18    Chattisgarh       42      M         7
  FirstName     State_name  Age_Num
0         A     Tamil Nadu       23
1         B      Karnataka       37
2         C     Tamil Nadu       35
3         D  Uttar Pradesh       26
4         E          Bihar       59
5         F          Bihar       48
6         G          Delhi       30
7         H  Uttar Pradesh       72
8    

In [5]:
# Question 4
df4 = pd.read_excel("Week 1 Dataset.xlsx")
df4 = df4.iloc[0:10, -2:]
print("iloc\n", df4)

iloc
   Sex  Number of siblings
0   M                   0
1   F                   3
2   F                   1
3   F                   4
4   M                   5
5   M                   6
6   F                   2
7   M                  10
8   F                   0
9   M                   7


In [6]:
# Question 5
df5 = pd.read_excel("Week 1 Dataset.xlsx")
df5 = df5.iloc[3:10, 1:5]
print("iloc\n", df5)

iloc
    Income per month          State  Age Sex
3                24  Uttar Pradesh   26   F
4                19          Bihar   59   M
5                21          Bihar   48   M
6                40          Delhi   30   F
7                20  Uttar Pradesh   72   M
8                30      Telangana   22   F
9                18    Chattisgarh   42   M


In [7]:
# Question 6
df6 = pd.read_excel("Week 1 Dataset.xlsx")
# print("Sum :: ", sum(df6["Number of siblings"]))
print("Count :: \n", df6["Number of siblings"].value_counts())

Count :: 
 0     2
10    1
7     1
6     1
5     1
4     1
3     1
2     1
1     1
Name: Number of siblings, dtype: int64


# Question 7

Dependant variables - number of siblings

Independant variables - Income per month,age

# Question 8

Each square shows correlation between variables in the dataset. As correlation value ranges from -1 to +1 so value close to 1 means more positively correlated the variables are, closer to 1 means stronger the relationship is.

A correlation closer to -1 is similar,but instead of both increasing one variable will decrease as the other increases.

According to graph shown, all diagonals shown as 100% in squares(cream white) are correlating each variable to itself which means they are perfectly or strongly correlated.

For rest, larger the percentage number, higher the correlation between two variables.

As 86% is more close to 100%, higher is the correlation between those variables.

-57% implies that the relationship between the variables are negatively correlated to each other.

For -77%, since its approaching to -100%, more strongly and negatively correlation is between two variables.